### ISSUE TITLE
ImportError: No module named GPIO

### ISSUE THREAD

**Issue by guillier** [adafruit/Adafruit_Python_GPIO#7] opened 2014-08-02 13:02 UTC
Hi,

I'm a bit puzzled by the meaning of the import in  <tt>Adafruit_GPIO/__init__.py</tt> which systematically throws an error: <tt>ImportError: No module named GPIO</tt>

I can think of 3 possible fixes (depending on the original idea behind this import):

* Removing it completely
* ```from Adafruit_GPIO.GPIO import *```
* ```from Adafruit_GPIO import *```

Regards,
François.

**Comment by tdicola** [comment] 2015-05-07 23:13
Coming back to this one a bit late, but I just merged in https://github.com/adafruit/Adafruit_Python_GPIO/pull/17 which should make the library work with Python 3.  Let me know if you see any issues--thanks!

**Closed by tdicola** 2015-05-07 23:13 UTC

**Comment by PaulDebus** [comment] 2015-09-20 18:09
I had this issue today on Python 2.7 
I replaced `from Adafruit_GPIO.GPIO import *` with `from .GPIO import *` in the `__init__.py` file and the other imports in `GPIO.py` and `I2C.py` accordingly. This has fixed it for me.
You have an idea to this?

**Comment by tdicola** [comment] 2015-09-21 17:13
That's odd, just to check what platform are you using (Pi, PC, etc.) and what Python minor version too (like 2.7.9, etc)?

**Comment by PaulDebus** [comment] 2015-09-21 17:22
I am using a Raspberry Pi 2 running Python 2.7.9 and Raspbian.
I did not install the module globally, I put it into the working folder and included it from there.

**Comment by tdicola** [comment] 2015-09-22 15:03
Oh gotcha thanks for clarifying the usage.  Let me raise a new issue to track switching over all the imports to proper python 2.7 & 3 relative ones.  It's good for python 2 & 3--I just want to spend a little time to test out a few things and make sure it works for all the library's uses.  Thanks!

**Comment by eimose** [comment] 2017-10-01 12:28
I received the error "ImportError: No module named 'Adafruit_PureIO'" when I tried to run `simpletest.py` for MCP9808 with python3 (`python3 simpletest.py`). I then installed Adafruit_PureIO with python3:
`git clone https://github.com/adafruit/Adafruit_Python_PureIO.git`
`cd Adafruit_Python_PureIO`
`sudo python3 setup.py install`
And this solved the problem issue.

**Comment by orkutsoft** [comment] 2018-08-03 20:51
i am using putty and remote desktop to connect to raspberry pi 
when i run program with  Adafruit_PCA9685 in putty command line that uses python 2.7 it runs the program but when when i use python 3.5.3 shell it gives import error   
i did every thing this conversation says
but 
SAME ERROR
"importerror no module named 'adafruit pca9685'"
